replicaCount: 1

image:
  repository: cr.yandex/crpt9bdjmglbhc0e3eis/frontend
  tag: 5f9eb61614c023b7e9ee2d7b9b3f292baba71043
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: task-manager.local
  path: /
  pathType: Prefix

imagePullSecrets: []