replicaCount: 1

image:
  repository: frontend
  tag: "1.0.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: task-manager.local
  path: /
  pathType: Prefix

imagePullSecrets: []