version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: task-manager-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

