{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-postgres-secret
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
{{- end }}
