image:
  repository: postgres
  tag: 16-alpine
  pullPolicy: IfNotPresent

postgres:
  database: task_manager
  username: postgres
  password: postgres

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 1Gi
  storageClassName: ""

resources: {}

probes:
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 5
