spring:
  application:
    name: task-manager

  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5430}/${POSTGRES_DB:task_manager}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  liquibase:
    change-log: classpath:db/changelog/changelog.yml
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5430}/${POSTGRES_DB:task_manager}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: health

server:
  port: 8080

#  management.endpoints.web.exposure.include=health
#  management.endpoint.health.show-details=always